services:
  app:
    build:
      context: .
      dockerfile: Dockerfile

    environment:
      ALLOWED_HOSTS: app,localhost
      CSRF_TRUSTED_ORIGINS: http://localhost:8001
      SECRET_KEY: django-insecure-development

      DB_HOST: postgres
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASSWORD: password
      DB_PORT: "5432"

    volumes:
      - static-files:/var/www/static

  proxy:
    image: nginx

    ports:
      - 8001:80

    volumes:
      - static-files:/var/www/static:ro
      - ./proxy/proxy-config.conf:/etc/nginx/conf.d/default.conf

volumes:
  static-files: null
